name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies with Upgraded Pip
        run: |
          python -m pip install --upgrade pip
          echo "--- Checking Pip Version ---"
          pip --version
          echo "--------------------------"
          pip install -e .[dev]

      - name: Run Tests with Explicit PYTHONPATH
        run: |
          PYTHONPATH=src pytest
